name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install gexiv2
      run: sudo apt update && sudo apt install libgexiv2-2 libgexiv2-dev -y
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
